[package]
name = "bindings"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = { git = "https://github.com/microsoft/windows-rs.git", branch = "impl_inner" }

[build-dependencies]
windows = { git = "https://github.com/microsoft/windows-rs.git", branch = "impl_inner" }
